### ISSUE TITLE
Problem with 'inputfile.fasta'

### ISSUE THREAD

**Issue by stella-gao** [WGLab/lncScore#8]
Hi,

I tried to prepare the training dataset, but when I run it, there is a problem:
```
No such file or directory at /cstor/xsede/users/xs-nksg/lncScore/tools/cpmodule/exon_extraction.pl line 31.
Traceback (most recent call last):
  File "tools/make_TrainingDat.py", line 506, in <module>
    inFiles = open(inPutFileName)
IOError: [Errno 2] No such file or directory: 'inputfile.fasta'
```
Do I need to create this file? Or do I need to change this name? If I need to change this name, which one should it be: the coding fasta file or non-coding fasta file? 
Thank you very much!

Best regards,
Stella

**Comment by zhaodoctor** [comment]
Can you send me your complete command that with all the paratemters?
I tried on my own computer, there is no problem. And when you run the 'make_TrainingDat.py', the 'inputfile.fasta' file would be generated in your current directory, and this file would be deleted when the 'make_TrainingDat.py' has been done. So, you can check your current directory to see that if there is a  file named as 'inputfile.fasta' ? 
If not, you can check that if there is a file named as 'temp_inputfile.fasta', which is used to generate the 'inputfile.fasta'. 
The  'temp_inputfile.fasta' is a file that combines the two '.fa' files  that you input, it is just a normal .fasta file, but the transcript id after the '>' has been shortened using the 'cpmodule/shortID.pl'. 
And the inputfile.fasta is the temp_inputfile.fasta combinded with the exon information extracted from your .gtf file, it is generated by the 'cpmodule/exon_extraction.pl' .
The data format in the 'inputfile.fasta' is as shown in the follows: 
 '>ENST00000378529.7       250 72 99 111 91 88 97 111 124 167 290
GACAGCGGCGGAAACGCGCACAGGCGCAGCTGCGTCCTCTGGCTCCGGGCCC..........'

**Comment by stella-gao** [comment]
Hi Dr. Zhao,

Thanks a lot for your comments.
My complete command is:
```
python tools/make_TrainingDat.py -m mrna.fa -l ncrna.fa -p 1 -x generated_Hexamer.tsv -g both.gtf -o resultfile
```
and the result is:
```
error!!
Traceback (most recent call last):
  File "make_TrainingDat.py", line 506, in <module>
    inFiles = open(inPutFileName)
IOError: [Errno 2] No such file or directory: 'inputfile.fasta'
```
Do I need to make a "temp_inputfile.fasta" by myself (combine these two .fa file)? It seems that if I do not have a "inputfile.fasta" file in the folder, I cannot run make_TrainingDat.py.

May I ask the exact format of the training datasets (.fa file)? 
Thank you very much!

**Comment by stella-gao** [comment]
Dear Dr. Zhao,

Sorry about the previous email.

I am very interested in your paper "lncScore: alignment-free identification
of lncRNA from assembled novel transcripts. " Your work is great!

I would like to do some related work based on it. But I have some problems
when running lncScore. Perhaps the format of my fasta files does not fit.

Could you please send me the human coding and noncoding training data fasta
files that you use to create Human_training.dat file as well as the command
you use to generate it.

Sorry to bother you. Since I have tried many times but still no idea what
is wrong with the data and commands I used.

Please help me!
Thank you very much! I appreciate your kind help a lot!

Best regards,
Stella

**Comment by zhaodoctor** [comment]
I have sent my data set to your email, and the format of my training datasets is shown as follows: 
`>ENST00000520296.5`
`CCGAACTGGGGCCCTGGCA......`
`>ENST00000378708.5`
`CAGCCTGGCTTGCTGGCTG.......`
`...` 
`>ENST00000454562.1`
`CAAGGGAGAGCTGTGTCCC.....`
`>ENST00000417917.1`
`GCAGGCTGAGGCTGAGGAG.......`
`...` 
The correponding .GTF file can be downloaded from the GENCODE, the complete sequences can be also downloaded from the GENCODE.

**Comment by stella-gao** [comment]
Yeah, the problem is solved now. The data format I used is a little different from yours. 
Thank you very much for your kind help!
